sudo: false
language: node_js
os:
  - linux
  - osx
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - iojs
after_success: npm run codeclimate
env:
  - secure: FXUg+tAnL6HAgJRrEYr6oDMICxGKe99Drfy0T+Hlr+md5iSMcSJbUa2UeZMNiBU6AaiiRWuta7c3mKYXFFOL7XOu+/j6vFm3mxVdSdpRu3Oq0zMd4HegbBZ35kMfZ6lRL+7UekZV/r5/BmRWyQKLEHVbRpPO4qF0sCUu5yGJj+WFcenxiJGStOFVGmYhlCUYSMsOITIeZEialAxqFsDBfo3aA948d/P6t05cPBnN0femP5llFyh9T/ZdJV4/fNtdcTz5aDeWmFYHZVzUeczSH/0JPydH4gBTVzxLxNn4R8k8rWwcG+7KLJL6S7QYXa+SGWdFFD77qeOnt/9Hn6fSzOunel+5UAAY6LSAg3CawHc9FT4YiVg/tsjeIq2JXHElnJCMlli4HQihtI78dTaYmKXXGXIwEkKkZ2RKe7Ftd9K1Shi3+0RjNT6zMICBJFT4ltV/xB8NkPotwbS4omSV8nI6NgCv/zQvLJIGp7ynx3EWE1Z6/wjk4gnaKTfv2u87++67eBYOfFOSg7A7BapOX2o6xs5phAAe3msrOAqoiwxXSG2Jfle3W6tfSVJaPGJNNQZfSKodwf5Wod6VTZEoGgfWuFL/BBS9X0dOqDOT4eaQ26nj1/ZKY8Zo9JU6wxm1tDhUtfqIJ2H66w9irAjwWK7MizF9jaGthM+C+igFqoM=
